services:
  server:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  client:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server
